services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "13307:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MY_SQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ticket