spring:
  application:
    name: consistence-control
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13307/ticket?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ${MY_SQL_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true